//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvct1
{
    using System;
    using System.Collections.Generic;
    
    public partial class kehuTable
    {
        public long id { get; set; }
        public string kehuCompanyName { get; set; }
        public string kehuContractName { get; set; }
        public string kehuTelPhone { get; set; }
        public string kehuOtherTel { get; set; }
        public string qq { get; set; }
        public string weixin { get; set; }
        public string email { get; set; }
        public Nullable<int> campusNum { get; set; }
        public string domain { get; set; }
        public string payMoneyStyle { get; set; }
        public System.DateTime firstQianDanDateTime { get; set; }
        public System.DateTime nextPayDateTime { get; set; }
        public string kehuInfoBeizhu { get; set; }
        public Nullable<int> saleStaffID { get; set; }
    }
}
