//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvct1
{
    using System;
    using System.Collections.Generic;
    
    public partial class liushuiTable
    {
        public long liushuiID { get; set; }
        public Nullable<int> moneyStyleID { get; set; }
        public Nullable<decimal> zhichuMoney { get; set; }
        public Nullable<decimal> shouruMoney { get; set; }
        public string liushuiShuoming { get; set; }
        public Nullable<int> jinbanrenStaffID { get; set; }
        public Nullable<System.DateTime> liushuiDateTime { get; set; }
        public Nullable<long> qiandanID { get; set; }
    }
}
