//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvct1
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuTable
    {
        public int id { get; set; }
        public string text { get; set; }
        public Nullable<int> fid { get; set; }
        public string url { get; set; }
        public string iconCls { get; set; }
        public Nullable<int> paixu { get; set; }
        public Nullable<int> levelID { get; set; }
        public Nullable<int> IsCss { get; set; }
        public Nullable<int> isquanxian { get; set; }
    }
}
