//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvct1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xw_OAEntities : DbContext
    {
        public xw_OAEntities()
            : base("name=xw_OAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gengjinTable> gengjinTable { get; set; }
        public DbSet<kehuTable> kehuTable { get; set; }
        public DbSet<liushuiTable> liushuiTable { get; set; }
        public DbSet<menuTable> menuTable { get; set; }
        public DbSet<moneyStyleTable> moneyStyleTable { get; set; }
        public DbSet<qianDanInfoTable> qianDanInfoTable { get; set; }
        public DbSet<staffTable> staffTable { get; set; }
        public DbSet<yixiangTable> yixiangTable { get; set; }
        public DbSet<yxKehuTable> yxKehuTable { get; set; }
    }
}
