//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvct1
{
    using System;
    using System.Collections.Generic;
    
    public partial class qianDanInfoTable
    {
        public long id { get; set; }
        public long kehuID { get; set; }
        public decimal shishouMoney { get; set; }
        public int saleStaffID { get; set; }
        public System.DateTime qianDanDateTime { get; set; }
        public int xinqianORxufei { get; set; }
        public string qiandanBeizhu { get; set; }
    }
}
