//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvct1
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffTable
    {
        public int staffID { get; set; }
        public string staffName { get; set; }
        public string staffPhone { get; set; }
        public string userName { get; set; }
        public string passwd { get; set; }
        public Nullable<int> userState { get; set; }
    }
}
