//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvct1
{
    using System;
    using System.Collections.Generic;
    
    public partial class yxKehuTable
    {
        public long id { get; set; }
        public string companyName { get; set; }
        public string contractName { get; set; }
        public string mPhone { get; set; }
        public string otherTel { get; set; }
        public string qq { get; set; }
        public string weixin { get; set; }
        public string email { get; set; }
        public int yixiangID { get; set; }
        public Nullable<System.DateTime> nextGenjinDateTime { get; set; }
        public Nullable<int> saleStaffID { get; set; }
        public Nullable<System.DateTime> recordInDateTime { get; set; }
        public string kehuInfoBeizhu { get; set; }
    }
}
